server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/catalog/ {
        proxy_pass http://catalog_service:5000/api/catalog/;
    }

    location /api/cart/ {
        proxy_pass http://cart_service:5000/api/cart/;
    }
}
